name: "Global Trust Bank"
accounts:
  - account_id: "ACCT000001"
    owner_name: "Emily Clark"
    balance_in_cents: 150000  # $1,500.00
    transactions:
      - "Deposit: $1,000.00"
      - "Withdrawal: $500.00"
      - "Interest: $50.00"
  - account_id: "ACCT000002"
    owner_name: "Michael Brown"
    balance_in_cents: 25000  # $250.00
    interest_rate: 2
    transactions:
      - "Deposit: $2,500.00"
